### ISSUE TITLE
Looking for new Maintainer

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/react-motion-drawer#14]
let me know if you're interested in maintaining this repo!

**Comment by mrkev** [comment]
not sure if he'd be up for it, but @Redmega has been pretty active 😅

**Comment by Redmega** [comment]
Haha, I'm just waiting on @KyleAMathews to approve the PRs 

This is a nifty repo and I'd be more than willing to maintain it.

**Comment by stoeffel** [comment]
haha. totally forgot about @KyleAMathews . I'm sorry. will add you as well @Redmega .thanks everyone for keeping this alive.

**Comment by Redmega** [comment]
Would it be bad form to accept my own PRs now?

**Comment by KyleAMathews** [comment]
Planning on reviewing it tomorrow. Generally good to get two sets of eyes
on something.

**Comment by Redmega** [comment]
Yeah, that's what I was waiting for. Sounds good, I'll hold off then.
