### ISSUE TITLE
Responsive width?

### ISSUE THREAD

**Issue by Redmega** [stoeffel/react-motion-drawer#17]
Seems like `width: number` limits it to pixel sizes.

Right now it requires using something like the `react-measure` package or some js to grab the window width in order to calculate a width.

Relative widths would be a useful feature to have. Any idea why only numbers were allowed to begin with?

**Comment by KyleAMathews** [comment]
Probably cause it was what was needed. Would be happy to accept a PR adding
support for percentage-based widths!

**Comment by Redmega** [comment]
I'll get on that.

**Comment by Redmega** [comment]
@KyleAMathews Please review that pull request and let me know if there's anything I need to change or refactor.
