### ISSUE TITLE
gh-page

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/react-motion-drawer#2]

**Comment by Redmega** [comment]
Hi @stoeffel, why was this closed? I think a github page for the demo would be useful ^^; 

It lets people quickly give it a spin without needing to clone and run it locally. I think it might be a good idea to make one.

**Comment by stoeffel** [comment]
Feel free to reopen, if you think it's helpful.

**Comment by Redmega** [comment]
I'll work on the branch for the gh page tonight after work. I think I'll need your help to set it up as I don't have access to the repo settings.

**Comment by KyleAMathews** [comment]
I vote we just use Netlify as it'll auto-build/deploy from Github so no extra work to keep the site up-to-date. I setup my fork of this project to do so (https://react-motion-drawer-kyle-fork.netlify.com/). If you haven't used Netlify yet, it's super easy to use. We could get a *.js.org name too to point to it to make things a bit more official.

**Comment by KyleAMathews** [comment]
If this is agreeable we'd just need @stoeffel for you to set this up.

**Comment by stoeffel** [comment]
what do I need to do?

**Comment by Redmega** [comment]
I use netlify for my (rather out of date) portfolio site. It's a great service and it'll integrate with the repo nicely. I agree, that's probably the best course of action. Better to let them webpack it on build instead of committing built files.

**Comment by KyleAMathews** [comment]
Go to https://www.netlify.com/, click "sign up", then link your account to Github which will pull a list of your repos, search/browse to this one and then create a site from it. For the build command use `npm run build-example`, and for the "Publish directory" use `example`. Then click "build your site". This will trigger an auto-build which should be done pretty quickly. Then go to the settings for the site and change the name to something like react-motion-drawer. That should be sufficient for now but it'd be easy to change the domain name to react-motion-drawer.js.org if someone wants to champion that.

@Redmega cool!

**Comment by KyleAMathews** [comment]
@Redmega yeah Github pages in retrospect was only really nice for Jekyll. Not having auto-building for anything else hurts its value.

**Comment by KyleAMathews** [comment]
@stoeffel oh and add the URL to the README.md + github project header of course.

**Comment by Redmega** [comment]
@KyleAMathews If we use Netlify to host, will js.org be possible? All the documentation I can find on it is for gh-pages.

**Comment by KyleAMathews** [comment]
Oh I guess not. I was just assuming they just took cname values but it looks like they assume you're using github pages. Oh well.

**Comment by KyleAMathews** [comment]
Oh oops, they do just support raw cname values — https://github.com/js-org/dns.js.org/blob/master/cnames_active.js netlify is on there a few times.

**Comment by Redmega** [comment]
@stoeffel Any chance you could either give @KyleAMathews or myself admin rights or sign up for netlify using your github (its free!) and then setting up continuous deployment? It's a super simple process, just need admin on the repo to do so...

If you sign up you can just click this to get it started. https://app.netlify.com/start/repos/stoeffel/react-motion-drawer. The build command is `npm run build-example`, and the publish folder is `example`. That should get us up and running with a live demo.

**Comment by stoeffel** [comment]
Done, https://react-motion-drawer.netlify.com/.

**Comment by Redmega** [comment]
Awesome, thanks!! This should automatically build `master` so we should be good to go from now on. I'll add the link to the readme as well.
