### ISSUE TITLE
React markup reuse warning

### ISSUE THREAD

**Issue by Redmega** [stoeffel/react-motion-drawer#25]
> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
(client) z-index:10000;width:122.69999999999999px
(server) z-index:10000;width:30%;padding-right:10

The calculation to width is probably causing this issue in apps with server-side rendering. Then again, this might be evidence of other issues in my project. **Further testing needed.**

**Comment by KyleAMathews** [comment]
yeah, probably using relative width with server rendered sites just should
be avoided.
