### ISSUE TITLE
Is there a way to stop mouse drag on drawer?

### ISSUE THREAD

**Issue by joeyzhao0113** [stoeffel/react-motion-drawer#29]
When I use mouse drag on the drawer, it will be moving with my mouse cursor. This behaviour is conflict with one of my component inside the drawer? Is there a way to disable this feather on drawer?

**Comment by Redmega** [comment]
Have you tried the following settings:

`noTouchOpen: bool` - can a user pan to open (default false)
`noTouchClose: bool` - can a user pan to close(default false)

**Comment by zhaoyi0113** [comment]
`noTouchOpen={true}
          noTouchClose={true}` works fine. Thanks
