### ISSUE TITLE
Drawer not showing

### ISSUE THREAD

**Issue by MidnightP** [stoeffel/react-motion-drawer#30]
I am having the following layout: 
```
<div>
  <Header />
	<div style={styles.layout}>
		<Drawer open={true} onChange={onChange} fadeOut right>
			<ul>
				<li>Home</li>
				<li>About</li>
				<li>Settings</li>
			</ul>
		</Drawer>
		{this.props.children}
	</div>
</div>
```

Am I doing something wrong?

**Comment by Redmega** [comment]
Can you share `styles.layout` and `onChange`?

**Comment by MidnightP** [comment]
```
const styles = {
	layout: {
		minHeight: '82%'
	}
}
```

```
const onChange = (e) => {
	return
}
```

**Comment by Redmega** [comment]
@MidnightP `onChange` should manage the external state of `open` for your Drawer. Haven't been able to test but I think this is it. Sorry for the delay I've been swamped lately.

**Comment by MidnightP** [comment]
I decided not to use a drawer for other reasons. Will look at this one the
future though. Thanks!

2017-06-05 16:33 GMT+02:00 Angel J Piscola <notifications@github.com>:

**Comment by Redmega** [comment]
No problem! Closing this issue then..
