### ISSUE TITLE
Padding on Right of Drawer While Open

### ISSUE THREAD

**Issue by liamfd** [stoeffel/react-motion-drawer#38]
# Description
Hey there, I've trying out this library and I think I've encountered an issue that there isn't an easy workaround for. I've noticed with a left drawer that when I try to open the drawer by clicking near the right edge of the screen, nothing happens. 

## Repro:
You can see it in the [demo](https://react-motion-drawer.netlify.com/). If you open the chrome inspector and inspect the container for the drawer, you'll see that the `padding-right: 20px` style is still applied while the drawer is closed. This appears to be the culprit, as when I remove it, the entire click area of the trigger area works. 

Is there a prop that I could use to modify the styles on that container? Alternatively, would it be possible to remove that padding when the drawer is closed? Changing the pointer-events might also do it, though I'm not sure how that would interact with the pan handler.

**Comment by Redmega** [comment]
`handleWidth` is the prop you're looking for. You should be able to click and drag on that padding to pull out the drawer. I just tested and it's not working for me so something else is going on...

In any case, if you don't want a handle, set `handleWidth` to `0`.

**Comment by liamfd** [comment]
Awesome, thanks!

**Comment by DanielPintilei** [comment]
Opening the drawer by panning from the device edge doesn't work for me.
Any updates on this?

**Comment by DanielPintilei** [comment]
I found out the bug was introduced in commit 9b0ad28737f31f8dd8ef6189f00b2b39097b80a9
It's because of the new wrapping div around the Hammer component.

**Comment by Redmega** [comment]
Thanks @DanielPintilei. I've been busy with work and haven't had the chance to look into this at all since then.

If you have a fix feel free to open a PR 💯  I'm not sure I'll have the chance over these holidays to work on it either.
