### ISSUE TITLE
`npm run serve` gives `Cannot GET /``

### ISSUE THREAD

**Issue by winkler1** [stoeffel/react-motion-drawer#4]
Hi-
 This looks interesting! Tried to run example, but can't figure out the path.  Getting a 404 (served from Express) at `/`. http://localhost:3000/static/bundle.js returns the bundled JS.
Thanks,
Jeff

**Comment by stoeffel** [comment]
Hi.
Thanks for your interest. did you point your browser to `localhost:3000/example/index.html`?
Otherwise try to change the port in [server.js#L9](https://github.com/stoeffel/react-motion-drawer/blob/master/example/server.js#L9)

**Comment by stoeffel** [comment]
Btw. Contributions are more than welcome! :smiley_cat:

**Comment by stoeffel** [comment]
Oups. this was my fault. Could you pull and try again? Thanks :blush:

**Comment by winkler1** [comment]
http://localhost:3000/index.html doesn't work either (that would have been embarrassing!)

Pulled your latest, but that didn't fix it. It does not get the index.html at all. Does `npm run serve` work for you?

**Comment by stoeffel** [comment]
yop it does now. Wait I will ask my friend if it works on his machine.

**Comment by stoeffel** [comment]
Try to set the port to `9999` and run `npm run serve` again.

**Comment by stoeffel** [comment]
I updated the readme (See [here](https://github.com/stoeffel/react-motion-drawer#example)).
You will have to git pull and run `npm install` again.

**Comment by winkler1** [comment]
Looks good, thanks. One nit -- if someone is running `npm run serve`, don't think they'll want to open another terminal window just to do `npm run open`. Instead, I think the last step in the README should just say `open http://localhost:9999/example/index.html`.

BTW, got this working - looks nice. Especially like how clicking outside the drawer dismisses it. Nice touch!

**Comment by stoeffel** [comment]
> Instead, I think the last step in the README should just say open http://localhost:9999/example/index.html.

done

> BTW, got this working - looks nice. Especially like how clicking outside the drawer dismisses it. Nice touch!

Thanks a lot :smile:

**Comment by jasan-s** [comment]
@stoeffel In the Readme GIF it looks as though you have implemented swipe to slide feature on the Drawer. however that does not seem the case on the downloaded example.
