### ISSUE TITLE
Enable user-select when noTouchOpen/noTouchClose

### ISSUE THREAD

**Issue by renatorib** [stoeffel/react-motion-drawer#40]
I'm creating a different behaviour to mobile/desk in my app.
When it's on desktop, I disable touchs with  `noTouchOpen` and `noTouchClose`, but I cannot add `user-select: auto` because internal drawer styles overrides any style in `drawerStyle` prop

**Comment by Redmega** [comment]
@renatorib So one thing you can do is add `!important` to the style in order to override it.

**Comment by renatorib** [comment]
I don't think it's the better solution. Also I don't use css, only plain styles

**Comment by Redmega** [comment]
@renatorib Definitely not ideal, but it is _a_ solution.

Now in `3.1.0` the drawerStyles will overwrite instead of assign to the drawer styles. This should fix your problem.
