### ISSUE TITLE
Probably a bug?

### ISSUE THREAD

**Issue by renatorib** [stoeffel/react-motion-drawer#41]
I don't understand this line:
https://github.com/stoeffel/react-motion-drawer/blob/master/lib/drawer.jsx#L143
```js
const { width } = this.calculateWidth()
```

Since `this.calculateWidth()` returns `number | string`
https://github.com/stoeffel/react-motion-drawer/blob/master/lib/drawer.jsx#L170-L175
```js
calculateWidth = () => {
  const width = this.props.width;
  return /\D/.test(width)
    ? document.body.clientWidth * (width.match(/\d*/) / 100)
    : width;
};
```

How it works? It works?

**Comment by Redmega** [comment]
100% right, this is a bug. It's working still because of various `|| 0`'s and whatnot.
