### ISSUE TITLE
[QUESTION]: How can i change the default settings of drawer?

### ISSUE THREAD

**Issue by sadan** [stoeffel/react-motion-drawer#45]
I want the drawer to start from a specific point on top. How can i change the top value in the default settings? 

Something like this

![image](https://user-images.githubusercontent.com/15120052/34320809-5f31ca8c-e823-11e7-89c4-faebcb072e16.png)

**Comment by Redmega** [comment]
I'll look into it this weekend, not able to check right now

**Comment by Redmega** [comment]
Sorry, things happened and I got distracted!

You can target it with css and `!important` to override the inline styles. Unfortunately the inline styles are calculated on the fly for the most part. I am looking into moving some of the more static styles to classes so they can be more easily overwritten.
