### ISSUE TITLE
How to change pan velocity

### ISSUE THREAD

**Issue by gagan0723** [stoeffel/react-motion-drawer#46]
In the demo, when the drawer is open, one can drag the drawer both left and right. How can I change the drag velocity so that it drags somewhat faster?

**Comment by MeXaaR** [comment]
change the config props to `config={{stiffness: 120}}` for exemple.
higher the stiffness, faster the drawer
change the config like in react-motion [https://github.com/chenglou/react-motion](url)

**Comment by Redmega** [comment]
As @MeXaaR said, you can pass the config props in order to change the react motion settings and play with the physics of the drawer.
