### ISSUE TITLE
Prevent click and scroll underneath drawer

### ISSUE THREAD

**Issue by vonwao** [stoeffel/react-motion-drawer#50]
Clicks on the grayed-out overlay generate click events in the component behind the drawer.

You can also scroll the content behind the drawer.  (I think in most cases that's not desirable).

**Comment by kevinthecity** [comment]
Also would love to see this

**Comment by Redmega** [comment]
So this is fixed by #51, but introduces some hard coded styling to the body, which might interfere with the users' styling. I'm not satisfied by that approach but I'm not sure if a better alternative exists, so I may merge it regardless.

**Comment by Redmega** [comment]
also just realized this is a duplicate of #24, so closing and moving conversation there.
