### ISSUE TITLE
Menu isnt interactive until several seconds after open

### ISSUE THREAD

**Issue by onionhammer** [stoeffel/react-motion-drawer#54]
After I swipe open the menu, and click a menu item, i often time have to tap multiple times before it registers unless I wait for several seconds after swiping the menu open

**Comment by Redmega** [comment]
What browser, operating system, machine specs, etc? I'm not facing that issue in the example or with any drawers in the wild -- might be your implementation is causing a lot of unnecessary re-rendering or something?

**Comment by onionhammer** [comment]
Hi @Redmega, it's relatively simple code to control the menu, so I can't imagine there's a lot of re-rendering going on. You can view the code running in the wild [here](https://demo.powercommandcloud.com/Dashboard), just swipe in from the left from a mobile resolution (under 900pix width)

Here's a snippet of the code

```js
<div>
  <a className="mobile-toggle"
     onClick={() => this.setState({ ...this.state, opened: true }) }>
    <FontAwesomeIcon icon={hamburger} />
  </a>
  <Drawer
    width={320}
    handleWidth={13}
    config={{
      stiffness: 1000,
      damping: 40
    }}
    open={this.state.opened}
    onChange={opened => this.setState({ ...this.state, opened }) }>
    <div className="site-filter">
      <RoutedAccountList />
    </div>
  </Drawer>
</div>
```

**Comment by onionhammer** [comment]
Actually i'm replacing react-motion-drawer with react-sidebar, which does not have this issue.. so you wont be able to see it on the link I placed before.

**Comment by Redmega** [comment]
Glad you found something that more closely suited your needs!
