### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by adrianha** [stoeffel/react-motion-drawer#8]
I am using react-motion-drawer on the right side. I've already added overflow:hidden on body but overflow still be seen. Any idea about this? (Problem occurred when i test iPhone's Safari. Anything works good when using it on desktop)

**Comment by Redmega** [comment]
Hi @adrianha, are you still facing this issue or can it be closed?

**Comment by adrianha** [comment]
i havent updated it to the latest version. I will close it for now. Thank you @Redmega
