### ISSUE TITLE
Bottom Drawer

### ISSUE THREAD

**Issue by adamjv90** [stoeffel/react-motion-drawer#9]
Just wondering if there were any plans on allowing the drawer to open from the bottom?

**Comment by stoeffel** [comment]
Nope, there is no plan atm. I actually don't use this component right now. If you are interested in implementing a bottom drawer, you are more than welcome.

**Comment by adamjv90** [comment]
have you moved too a different drawer component? i will deffinatly submit a pull request when i get around to modifing the source of this component if i cant find something pre build already.

**Comment by stoeffel** [comment]
> have you moved too a different drawer component? 

nope, I just don't have a use-case for it atm.

**Comment by Redmega** [comment]
This is not within scope for this project at the moment. Please feel free to open a PR implementing a bottom drawer approach.
